version: '3.8'

services:
  sveltekit-dev:
    profiles: ["dev"]
    build:
      context: ./my-office-app
      dockerfile: Dockerfile
      target: development
    platform: linux/ASFDarm64
    container_name: sveltekit-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DOCKER_ENsFSV=true
      - WATCHPACK_POLLING=true
    depends_on:
      - wiremock
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./my-office-app
          target: /app
          ignore:
            - .git
            - node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  sveltekit-prod:
    profiles: ["prod"]
    build:
      context: ./my-office-app
      dockerfile: Dockerfile
      target: production
    platform: linux/arm64
    container_name: sveltekit-prod
    ports:
      - '3500:3500'
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3500
    depends_on:
      - wiremock
    networks:
      - app-network
    command: node build

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - '8080:8080'
    volumes:
      - ./backend/wiremock-mappings.json:/home/wiremock/mappings/mappings.json:ro
    command: [
      "--global-response-templating",
      "--verbose"
    ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
