version: '3.8'

services:
  sveltekit:
    build:
      context: ./my-office-app
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: sveltekit
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    depends_on:
      - wiremock
    networks:
      - app-network

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - '8080:8080'
    volumes:
      - ./backend/wiremock-mappings.json:/home/wiremock/mappings/mappings.json:ro
    command: [
      "--global-response-templating",
      "--verbose"
    ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
